name: CI
on:
  push:
    branches: [ develop ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Snyk
        uses: snyk/actions@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
